### ISSUE TITLE
Sieve.make/1に1000を与えると範囲エラーになる

### ISSUE THREAD

**Issue by yellowsman** [yellowsman/sieve_of_eratosthenes#1]
```elixir
iex(2)> make = Sieve.make(1000)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: out of range

    :erlang.setelement(1002, {true, true, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, true, false, true, false, false, false, true, false, false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, false, true, false, true, false, false, false, true, false, false, ...}, false)
    (sieve 0.1.0) lib/sieve.ex:21: anonymous fn/2 in Sieve.screen/3
    (elixir 1.13.0) lib/enum.ex:4135: Enum.reduce_range/5
    (sieve 0.1.0) lib/sieve.ex:21: Sieve.screen/3
```

**Comment by yellowsman** [comment]
うまくいく値とそうじゃない値がある。

```elixir
iex(8)> make = Sieve.make(100)
{true, true, false, false, false, false, false, false, false, false, false,
 true, false, true, false, false, false, true, false, true, false, false, false,
 true, false, false, false, false, false, true, false, true, false, false,
 false, false, false, true, false, false, false, true, false, true, false,
 false, false, true, false, false, ...}
iex(9)> make = Sieve.make(101)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: out of range

    :erlang.setelement(103, {true, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, ...}, false)
    (sieve 0.1.0) lib/sieve.ex:21: anonymous fn/2 in Sieve.screen/3
    (elixir 1.13.0) lib/enum.ex:4135: Enum.reduce_range/5
    (sieve 0.1.0) lib/sieve.ex:21: Sieve.screen/3
iex(9)> make = Sieve.make(102)
{true, true, false, false, false, false, false, false, false, false, false,
 true, false, true, false, false, false, true, false, true, false, false, false,
 true, false, false, false, false, false, true, false, true, false, false,
 false, false, false, true, false, false, false, true, false, true, false,
 false, false, true, false, false, ...}
iex(10)> make = Sieve.make(103)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: out of range

    :erlang.setelement(105, {true, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, ...}, false)
    (sieve 0.1.0) lib/sieve.ex:21: anonymous fn/2 in Sieve.screen/3
    (elixir 1.13.0) lib/enum.ex:4135: Enum.reduce_range/5
    (sieve 0.1.0) lib/sieve.ex:21: Sieve.screen/3
iex(10)> make = Sieve.make(104)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: out of range

    :erlang.setelement(106, {true, true, false, false, false, true, false, true, false, false, false, true, false, true, false, false, false, true, false, true, false, false, false, true, false, true, false, false, false, true, false, true, false, false, false, true, false, true, false, false, false, true, false, true, false, false, false, true, false, true, ...}, false)
    (sieve 0.1.0) lib/sieve.ex:21: anonymous fn/2 in Sieve.screen/3
    (elixir 1.13.0) lib/enum.ex:4135: Enum.reduce_range/5
    (sieve 0.1.0) lib/sieve.ex:21: Sieve.screen/3
iex(10)> make = Sieve.make(105)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: out of range

    :erlang.setelement(107, {true, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, ...}, false)
    (sieve 0.1.0) lib/sieve.ex:21: anonymous fn/2 in Sieve.screen/3
    (elixir 1.13.0) lib/enum.ex:4135: Enum.reduce_range/5
    (sieve 0.1.0) lib/sieve.ex:21: Sieve.screen/3
iex(10)> make = Sieve.make(106)
{true, true, false, false, false, false, false, false, false, false, false,
 true, false, true, false, false, false, true, false, true, false, false, false,
 true, false, false, false, false, false, true, false, true, false, false,
 false, false, false, true, false, false, false, true, false, true, false,
 false, false, true, false, false, ...}
```

**Comment by yellowsman** [comment]
修正したのでクローズ
